# For now, coverage is disabled because we don't have tests...
language: python
python:
  - "2.7"
#  - "3.3"
# command to install dependencies
install:
  - pip install -r requirements.txt
#  - pip install coveralls
  - pip install flake8

# command to run tests
script:
# - coverage run --source=. $(which nosetests)
 - flake8 debileweb/
after_success: coveralls
